services:
  - type: web
    name: inventory-production-tracker
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=75.0 -XX:+ExitOnOutOfMemoryError
      - key: DB_HOST
        fromDatabase:
          name: inventory-production-tracker-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: inventory-production-tracker-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: inventory-production-tracker-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: inventory-production-tracker-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: inventory-production-tracker-db
          property: password

databases:
  - name: inventory-production-tracker-db
    plan: free
    databaseName: inventorytracker
    user: inventorytracker
